[package]
name = "nv1-ros-communicator"
version = "0.1.0"
edition = "2021"

[dependencies]
corncobs = "0.1.3"
futures = "0.3.30"
r2r.workspace = true
serialport = "4.5.0"
tokio = { version = "1.39.3", features = ["full"] }
